baseURL = 'https://jto.dev/'
languageCode = 'en-us'
title = 'Johnny To'
contentDir = 'content'
enableEmoji = true

[params]
  subtitle = 'Dive into my space'

[outputFormats.Resume]
  mediaType = "text/html"
  baseName = "index" # Ensures it outputs as `index.html`
  isPlainText = false
  rel = "resume"

[module]
  [[module.imports]]
	path = "github.com/colinwilson/lotusdocs"
	disable = false
  [[module.imports]]
	path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
	disable = false

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true

# LotusDocs
[params.social]
  github = "348ab1a8-424a-43d8-b463-8e925d751c7f"

[params.footer]
  copyright = "2025 Copyright \u00A9 Johnny To"

[params.docs]
  title = "Digital Garden"
  darkMode = true

[params.flexsearch]
  enabled = true
  tokenize = "strict"