baseURL = 'https://jto.dev/'
languageCode = 'en-us'
title = 'Johnny To'

[params]
  subtitle = 'Dive into my space'

[outputFormats.Resume]
  mediaType = "text/html"
  baseName = "index" # Ensures it outputs as `index.html`
  isPlainText = false
  rel = "resume"
